"""Account Codes

Revision ID: b3d225d3743d
Revises: 981aea8653ee
Create Date: 2024-04-26 04:08:54.000313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d225d3743d'
down_revision: Union[str, None] = '981aea8653ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_activation_codes', sa.Column('status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('activation_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_time')
    op.drop_column('account_activation_codes', 'status')
    # ### end Alembic commands ###
